CREATE TABLE Pets (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(50) NOT NULL UNIQUE,
    Type NVARCHAR(50) NOT NULL,
    Breed NVARCHAR(50) NOT NULL,
    Sex NVARCHAR(10) NOT NULL
);